#ifndef __CUST_PANTECH_PMIC_H__
#define __CUST_PANTECH_PMIC_H__

#define FEATURE_PANTECH_PMIC_CHARGER_OFFLINE
#define FEATURE_PANTECH_PMIC_BOOT_POWER_ON_PROCESS
#define FEATURE_PANTECH_PMIC_PMIC_HW_REVISION	// 20130528. MKS. PMIC HW rev.
#define FEATURE_PANTECH_PMIC_SMPL //20140103 ryu. It is to operate SMPL. It changes trustzone setting value.
#define FEATURE_PANTECH_PMIC_PWR_KEY_LK //p13787 ryu
//#define FEATURE_PANTECH_PMIC_LK_THREAD
//#define FEATURE_POWER_ON_OFF_TEST 
//#define FEATURE_PANTECH_PMIC_BATTERY_CHARGING_DISCHARGING_TEST 
#define FEATURE_PANTECH_PMIC
#if defined(FEATURE_PANTECH_PMIC)
#define FEATURE_PANTECH_PMIC_SHARED_DATA
#define FEATURE_PANTECH_PMIC_HW_REVISION
#endif

#define FEATURE_PANTECH_PMIC_MONITOR_TEST 
#define FEATURE_PANTECH_PMIC_MAX17058
#define FEATURE_PANTECH_PMIC_CHARGER_SMB349
#define FEATURE_PANTECH_PMIC_AUTO_PWR_ON       //20130610 djjeon PMIC  10% offline charging  Auto power on
#define FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_FINGERPRINT //20130701 sayuss : charging limitation with FigerPrint Device
#define FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_LCD //20130701 sayuss : charging limitation with LCD ON
#define FEATURE_PANTECH_PMIC_EOC //end of recahrigng
#define FEATURE_PANTECH_PMIC_ABNORMAL //Abnormal charger
#define FEATURE_PANTECH_PMIC_BMS_TEST   
#define	FEATURE_PANTECH_PMIC_OTG //otg current smb349 250mA setting
#define FEATURE_PANTECH_PMIC_CHARGING_DISABLE	// 20130711. LS1. MKS. Charging disable for Factory Test.
#define FEATURE_PANTECH_PMIC_BOOT_CHARGER_NO_WAIT	//20130730 P14787 djjeon auto trickle disable
#define FEATURE_PANTECH_PMIC_UVLO //20130701 sayuss : charging limitation with LCD ON
#define FEATURE_PANTECH_PMIC_LIMIT_WITH_EF56S  ////20130810 sayuss : HW Request limit for EF56S
#define FEATURE_PANTECH_PMIC_OTG_UVLO	// 20130830 skkim p14200@LS1 : SMB347 OTG UVLO Status
#define FEATURE_PANTECH_PMIC_PHYSICAL_DROP	// 20130831 skkim p14200@LS1 : Physical Dropping WatchDog RESET Prevent
#define FEATURE_PANTECH_PMIC_USBIN_DROP_WORKAROUND // 20130828. MKS. USBIN voltage drop workaround for SMB347
#define FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_TSENSOR // 20130916 Tsensor current limit 
#define FEATURE_PANTECH_PMIC_SPMI_SW_WORKAROUND // 20131001 sayuss : SW modification for MSM8974 SPMI False detection of SSC
#define FEATURE_PANTECH_PMIC_LED //20131021 lee : LED team max17058/battery status funtion offer 
#define FEATURE_PANTECH_PMIC_I2C_LOCK  // 20131115 kyounghun : It will protected i2c transport.


#if defined(T_EF56S) || defined(T_EF57K) || defined(T_EF58L) 

#if (CONFIG_BOARD_VER <= CONFIG_WS10)
#undef FEATURE_PANTECH_PMIC_CHARGING_DISABLE
#undef FEATURE_PANTECH_PMIC_CHARGER_SMB349
#undef FEATURE_PANTECH_PMIC_BMS_TEST
#undef FEATURE_PANTECH_PMIC_ABNORMAL
#undef FEATURE_PANTECH_PMIC_OTG
#undef FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_FINGERPRINT
#undef FEATURE_PANTECH_PMIC_AUTO_PWR_ON
#undef FEATURE_PANTECH_PMIC_PWR_KEY_LK
#undef FEATURE_PANTECH_PMIC_LK_THREAD
#endif//(CONFIG_BOARD_VER <= CONFIG_WS10)

#if (CONFIG_BOARD_VER < CONFIG_TP10)
#undef FEATURE_PANTECH_PMIC_OTG
#endif//(CONFIG_BOARD_VER < CONFIG_TP10)

#undef FEATURE_PANTECH_PMIC_EOC
#undef FEATURE_PANTECH_PMIC_OTG_UVLO
#undef FEATURE_PANTECH_PMIC_PHYSICAL_DROP
#undef FEATURE_PANTECH_PMIC_USBIN_DROP_WORKAROUND
#undef FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_TSENSOR
#undef FEATURE_PANTECH_PMIC_SPMI_SW_WORKAROUND
#undef FEATURE_PANTECH_PMIC_LED
#undef FEATURE_PANTECH_PMIC_I2C_LOCK
#undef FEATURE_PANTECH_PMIC_PWR_KEY_LK
#undef FEATURE_PANTECH_PMIC_LK_THREAD
#endif 

#if defined(T_EF59S) || defined(T_EF59K) || defined(T_EF59L)
#if (CONFIG_BOARD_VER <= CONFIG_WS20)
#undef FEATURE_PANTECH_PMIC_USBIN_DROP_WORKAROUND
#undef FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_TSENSOR
#endif
#undef FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_LCD
#undef FEATURE_PANTECH_PMIC_LIMIT_WITH_EF56S
#undef FEATURE_PANTECH_PMIC_I2C_LOCK
#undef FEATURE_PANTECH_PMIC_PWR_KEY_LK
#undef FEATURE_PANTECH_PMIC_LK_THREAD
#endif//(CONFIG_BOARD_VER <= CONFIG_WS20)

#if defined(T_EF60S) || defined(T_EF65S) || defined(T_EF61K) || defined(T_EF62L)
#undef FEATURE_PANTECH_PMIC_CHARGE_LIMIT_WITH_LCD
#undef FEATURE_PANTECH_PMIC_LIMIT_WITH_EF56S
#undef FEATURE_PANTECH_PMIC_PHYSICAL_DROP
#undef FEATURE_PANTECH_PMIC_LK_THREAD
#endif

#if defined(T_EF63S) || defined(T_EF63K) || defined(T_EF63L)
#undef FEATURE_PANTECH_PMIC_CHARGER_SMB349
#endif

#endif // __CUST_PANTECH_PMIC_H__ end

