#ifndef __CUST_PANTECH_DRM_H__
#define __CUST_PANTECH_DRM_H__

// p12455 - FEATURE_PANTECH_HOPPIN_DRM
#define FEATURE_PANTECH_HOPPIN_DRM

// p12455 - FEATURE_PANTECH_MUSIC_DRM
#define FEATURE_PANTECH_MUSIC_DRM

#endif
